"""C code generation for SOS filters (pure rendering: data -> C text).

No I/O, no DSP. Turns already-computed SOS coefficients + metadata into the
text of an aggregated C header. A single `filter_sos.h` holds, for every
filter, UPPERCASE `#define` macros only -- no init functions, no `static`
arrays.

Per second-order section the runtime library expects 5 coefficients
(denominator normalized, a0 = 1):

    b0, b1, b2, a1, a2

scipy SOS rows are [b0, b1, b2, a0, a1, a2]; this module drops a0.

Odd-order filters: scipy emits a first-order section as a biquad with
b2 = a2 = 0, i.e. [b0, b1, 0, a1, 0]. No special handling is needed; such
sections are just annotated "(1st-order)" in the generated comment.
"""
from __future__ import annotations

import re

import numpy as np

HEADER_TOP = """\
/**
 * @file  filters_coeffs.h
 * @brief Auto-generated SOS filter coefficients and parameters.
 *
 * Generated by tools/convert.py -- DO NOT EDIT BY HAND.
 *
 * Standalone data header (only #define macros). Pair it with the runtime
 * library header in your own code:
 *     #include "sos_filter.h"       // the SOS DF2T runtime library
 *     #include "filters_coeffs.h"   // this file
 *     static const float32_t c[] = FILTER_SOS_<NAME>_COEFFS;
 *
 * Per filter, UPPERCASE #define macros only:
 *   FILTER_SOS_<NAME>_N_SECTIONS   section count
 *   FILTER_SOS_<NAME>_COEFFS       brace initializer, 5 per section: b0,b1,b2,a1,a2
 *   FILTER_SOS_<NAME>_<PARAM>      numeric params (ORDER, FS, ...)
 */
#ifndef FILTERS_COEFFS_H
#define FILTERS_COEFFS_H
"""

HEADER_BOTTOM = "\n#endif /* FILTERS_COEFFS_H */\n"


def sanitize(name: str) -> str:
    """Turn a filter/param name into a valid UPPERCASE C identifier fragment."""
    ident = re.sub(r"[^0-9a-zA-Z]+", "_", str(name)).strip("_").upper()
    if not ident:
        raise ValueError(f"name {name!r} sanitizes to empty identifier")
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def sos_to_c5(sos: np.ndarray) -> np.ndarray:
    """Convert a scipy SOS array (N x 6) to the lib's (N x 5) float32 layout."""
    sos = np.asarray(sos, dtype=np.float64)
    if sos.ndim != 2 or sos.shape[1] != 6:
        raise ValueError(f"expected SOS array of shape (N, 6), got {sos.shape}")
    if not np.allclose(sos[:, 3], 1.0, atol=1e-9):
        raise ValueError("sections are not normalized (a0 != 1)")
    return sos[:, [0, 1, 2, 4, 5]].astype(np.float32)  # [b0, b1, b2, a1, a2]


def _is_first_order(sec5: np.ndarray) -> bool:
    """A section is first-order when b2 == 0 and a2 == 0 (scipy's convention)."""
    return sec5[2] == 0.0 and sec5[4] == 0.0


def _fmt_param(value) -> str:
    """Format a numeric param: integral values as int, else as a float."""
    if isinstance(value, bool):
        raise TypeError("bool is not a numeric parameter")
    f = float(value)
    return str(int(f)) if f.is_integer() else repr(f)


def render_coeffs_macro(prefix: str, sec5: np.ndarray) -> str:
    """Render the multi-line FILTER_SOS_<NAME>_COEFFS macro."""
    lines = [f"#define {prefix}_COEFFS {{ \\"]
    n = sec5.shape[0]
    for i, sec in enumerate(sec5):
        vals = ", ".join(f"{v:.9e}f" for v in sec)
        tag = f"section {i}" + (" (1st-order)" if _is_first_order(sec) else "")
        last = i == n - 1
        sep = "" if last else ","
        cont = " }" if last else " \\"
        lines.append(f"    {vals}{sep}  /* {tag} */{cont}")
    return "\n".join(lines)


def _comment_block(name: str, description: str | None) -> str:
    """A /* ... */ block: the name, then each description line."""
    lines = [name]
    if description:
        lines += description.splitlines()
    body = "\n".join(f" * {ln}".rstrip() for ln in lines)
    return f"\n/*\n{body}\n */"


def render_filter_block(name: str, sos: np.ndarray, *,
                        params: dict | None = None,
                        description: str | None = None) -> str:
    """Render the full macro block for one filter."""
    sec5 = sos_to_c5(sos)
    prefix = f"FILTER_SOS_{sanitize(name)}"

    out = [_comment_block(name, description),
           f"#define {prefix}_N_SECTIONS {sec5.shape[0]}",
           render_coeffs_macro(prefix, sec5)]
    for key, value in (params or {}).items():
        if value is None:
            continue
        try:
            out.append(f"#define {prefix}_{sanitize(key)} {_fmt_param(value)}")
        except (TypeError, ValueError):
            continue  # skip non-numeric params (already in the comment)
    return "\n".join(out) + "\n"


def render_header(filters: list[dict]) -> str:
    """Render the whole filter_sos.h.

    filters: list of {"name": str, "sos": np.ndarray,
                      "params": dict|None, "description": str|None}
    """
    blocks = [render_filter_block(f["name"], f["sos"],
                                  params=f.get("params"),
                                  description=f.get("description"))
              for f in filters]
    return HEADER_TOP + "".join(blocks) + HEADER_BOTTOM


__all__ = ["sanitize", "sos_to_c5", "render_filter_block", "render_header"]
